package uk.co.controlnetworksolutions.elitedali2.dali.defs;

public class DaliQueryCodes {
   public static final int STATUS = 144;
   public static final int CONTROL_GEAR = 145;
   public static final int LAMP_FAILURE = 146;
   public static final int LAMP_POWER_ON = 147;
   public static final int LIMIT_ERROR = 148;
   public static final int RESET_STATE = 149;
   public static final int MISSING_SHORT_ADDRESS = 150;
   public static final int VERSION_NUMBER = 151;
   public static final int CONTENT_DTR = 152;
   public static final int DEVICE_TYPE = 153;
   public static final int PHYSICAL_MINIMUM_LEVEL = 154;
   public static final int POWER_FAILURE = 155;
   public static final int CONTENT_DTR1 = 156;
   public static final int CONTENT_DTR2 = 157;
   public static final int ACTUAL_LEVEL = 160;
   public static final int MAX_LEVEL = 161;
   public static final int MIN_LEVEL = 162;
   public static final int POWER_ON_LEVEL = 163;
   public static final int SYSTEM_FAILURE_LEVEL = 164;
   public static final int FADE_TIME_FADE_RATE = 165;
   public static final int SCENE_LEVEL_0 = 176;
   public static final int SCENE_LEVEL_1 = 177;
   public static final int SCENE_LEVEL_2 = 178;
   public static final int SCENE_LEVEL_3 = 179;
   public static final int SCENE_LEVEL_4 = 180;
   public static final int SCENE_LEVEL_5 = 181;
   public static final int SCENE_LEVEL_6 = 182;
   public static final int SCENE_LEVEL_7 = 183;
   public static final int SCENE_LEVEL_8 = 184;
   public static final int SCENE_LEVEL_9 = 185;
   public static final int SCENE_LEVEL_10 = 186;
   public static final int SCENE_LEVEL_11 = 187;
   public static final int SCENE_LEVEL_12 = 188;
   public static final int SCENE_LEVEL_13 = 189;
   public static final int SCENE_LEVEL_14 = 190;
   public static final int SCENE_LEVEL_15 = 191;
   public static final int GROUPS_0_7 = 192;
   public static final int GROUPS_8_15 = 193;
   public static final int RANDOM_ADDRESS_H = 194;
   public static final int RANDOM_ADDRESS_M = 195;
   public static final int RANDOM_ADDRESS_L = 196;
   public static final int READ_MEMORY_LOCATION = 197;
   public static final int EXTENDED_VERSION_NUMBER = 255;
}
